coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

# Badge color thresholds
# Green: >= 80%, Yellow: 60-79%, Red: < 60%
