coverage:
  # Badge 顏色範圍（官方設定方式）
  # 60% 以下紅色，80% 以上綠色
  range: "60...80"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
