"""Tests for pinned Blind-v2 input-only source pilots."""
# zhtw:disable  # 測試來源必須保持簡體

from __future__ import annotations

import hashlib
import io
import json
import tarfile
from pathlib import Path
from typing import Any

import pytest

from scripts.benchmark_metrics import canonical_json_bytes
from scripts.import_blind_v2_source_pilot import (
    build_dataset,
    normalize_input,
    parse_aosp_strings,
    parse_cdc_pages,
    parse_ftc_heads_up_pages,
    parse_ftc_small_business_pages,
    parse_massive,
    parse_nps_acadia_html,
    parse_osha_pdf,
    parse_project_original,
    parse_ready_gov_html,
    parse_vscode_loc,
    validate_dataset,
)
from scripts.validate_benchmark_assets import validate_manifest

ROOT = Path(__file__).resolve().parents[1]
ACCURACY_ROOT = ROOT / "benchmarks" / "accuracy"
MANIFESTS = ACCURACY_ROOT / "manifests"
EXTERNAL = ACCURACY_ROOT / "external"
FORBIDDEN_KEYS = {"expected", "acceptable", "annotation", "output", "normalized_output"}


def flores_archive(dev: list[str], devtest: list[str]) -> bytes:
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as archive:
        for name, lines in (
            ("./flores200_dataset/dev/zho_Hans.dev", dev),
            ("./flores200_dataset/devtest/zho_Hans.devtest", devtest),
        ):
            content = ("\n".join(lines) + "\n").encode()
            info = tarfile.TarInfo(name)
            info.size = len(content)
            archive.addfile(info, io.BytesIO(content))
    return buffer.getvalue()


def manifest(source_id: str, source: Path) -> dict[str, Any]:
    return {
        "id": source_id,
        "raw_sha256": {
            "https://example.test/source": hashlib.sha256(source.read_bytes()).hexdigest()
        },
        "normalized_path": "unused.json",
        "output_license": "CC BY-SA 4.0",
        "attribution": "Fixture contributors.",
        "modification_notice": "Input-only fixture extraction.",
        "upstream_revision": "fixture-revision",
    }


def find_forbidden_keys(value: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(value, dict):
        for key, child in value.items():
            if key in FORBIDDEN_KEYS:
                found.add(key)
            found.update(find_forbidden_keys(child))
    elif isinstance(value, list):
        for child in value:
            found.update(find_forbidden_keys(child))
    return found


def test_flores_import_is_deterministic_input_only_and_deduplicated(tmp_path: Path) -> None:
    source = tmp_path / "flores.tar.gz"
    source.write_bytes(flores_archive(["开发  工具", "重复句"], ["重复句", "用户界面"]))
    fixture = manifest("flores-200-zho-hans-v1", source)

    first = build_dataset(fixture, source_file=source)
    second = build_dataset(fixture, source_file=source)

    assert first["stats"] == {
        "raw_cases": 4,
        "eligible_pending_review": 3,
        "by_split": {"dev": 2, "devtest": 1},
        "exclusions": {"exact_duplicate_within_source": 1},
    }
    assert first["cases"][0]["input"] == "开发 工具"
    assert first["cases"][0]["classification"] == {
        "domain": None,
        "risk": None,
        "status": "needs_input_only_review",
    }
    assert find_forbidden_keys(first) == set()
    assert validate_dataset(first) == []
    assert canonical_json_bytes(first) == canonical_json_bytes(second)


def test_ud_cfl_import_rejects_incomplete_conllu(tmp_path: Path) -> None:
    source = tmp_path / "cfl.conllu"
    source.write_text(
        "# sent_id = missing-text\n1\t文字\t_\tX\t_\t_\t0\troot\t_\t_\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError, match="missing sent_id or text"):
        build_dataset(manifest("ud-chinese-cfl-v1", source), source_file=source)


def test_normalization_does_not_convert_script() -> None:
    assert normalize_input("开发  软件\r\n接口") == "开发 软件 接口"


def test_massive_parser_extracts_only_input_provenance_fields() -> None:
    rows = [
        {
            "id": "7",
            "locale": "zh-CN",
            "partition": "train",
            "scenario": "audio",
            "intent": "audio_volume_mute",
            "utt": "暂停十秒钟",
            "annot_utt": "暂停 [time : 十秒钟]",
            "worker_id": "35",
            "judgments": [{"worker_id": "0", "grammar_score": 4}],
        }
    ]
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as archive:
        content = ("\n".join(json.dumps(row, ensure_ascii=False) for row in rows)).encode()
        info = tarfile.TarInfo("1.0/data/zh-CN.jsonl")
        info.size = len(content)
        archive.addfile(info, io.BytesIO(content))

    assert parse_massive(buffer.getvalue()) == [("train", "7", "暂停十秒钟")]


def test_vscode_loc_parser_keeps_structured_ui_text_only() -> None:
    source = {
        "": [
            "Copyright (c) Microsoft Corporation. All rights reserved.",
            "Do not edit this file. It is machine generated.",
        ],
        "version": "1.0.0",
        "contents": {
            "module/two": {
                "url": "请前往 https://example.test 查看。",
                "placeholder": "{0}",
                "multiline": "第一行\n第二行",
            },
            "module/one": {
                "open": "打开辅助视图",
                "error": "无法保存文件: {0}",
            },
        },
    }

    rows = parse_vscode_loc(json.dumps(source, ensure_ascii=False).encode())

    assert [row[2] for row in rows] == ["无法保存文件: {0}", "打开辅助视图"]
    assert all(row[0] == "language_pack" for row in rows)
    assert all(row[1].startswith("entry-") for row in rows)


def test_aosp_parser_keeps_stable_single_line_ui_strings() -> None:
    content = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2006, The Android Open Source Project
Licensed under the Apache License, Version 2.0 -->
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
  <string name="save" msgid="1">"保存文件"</string>
  <string name="retry" msgid="2"
    >"无法连接。请在 <xliff:g id="SECONDS">%1$d</xliff:g> 秒后重试。"</string>
  <string name="url" msgid="3">"请访问 https://example.test"</string>
  <string name="short" msgid="4">"未知"</string>
  <string name="escaped_newline" msgid="5">"第一行\\n第二行"</string>
  <string name="bare_domain" msgid="6">"请访问 google.com"</string>
</resources>""".encode()

    rows = parse_aosp_strings(content)

    assert [row[2] for row in rows] == ["保存文件", "无法连接。请在 %1$d 秒后重试。"]
    assert all(row[0] == "framework_ui" for row in rows)
    assert all(row[1].startswith("string-") for row in rows)


def test_cdc_pdf_parser_joins_layout_wraps_and_keeps_complete_sentences() -> None:
    pages = [
        "标题 佩戴口罩。 与其他人保持至少 6 英尺的距离。 可访问版本：https://example.test",
        (
            "标题 请勿与家里的其他人共用 碗 碟 、水 杯。"
            " 遵循当地 卫生部门的指示。 如果某人出现 呼吸困难。"
        ),
    ]

    rows = parse_cdc_pages("cdc-stacks-111808-v1", pages)

    assert [row[2] for row in rows] == [
        "佩戴口罩。",
        "与其他人保持至少 6 英尺的距离。",
        "请勿与家里的其他人共用碗碟、水杯。",
        "遵循当地卫生部门的指示。",
        "呼吸困难。",
    ]


def test_ftc_parser_removes_layout_navigation_and_joins_cross_page_sentence() -> None:
    pages = ["诈骗与你的小型企业: 企业指南"] + [""] * 9
    pages[1] = (
        "诈骗与你的小型企业: 企业指南\n1\n► 诈骗犯的伎俩\n"
        "● 诈骗犯会营造一种紧迫感，甚至施以威胁。\n"
        "请前往 ftc.gov/example 查阅更多信息。\n"
        "他们会要求你将企"
    )
    pages[2] = "诈骗与你的小型企业: 企业指南\n2\n业资料交给对方。"

    rows = parse_ftc_small_business_pages(pages)

    assert [row[2] for row in rows] == [
        "诈骗犯会营造一种紧迫感，甚至施以威胁。",
        "他们会要求你将企业资料交给对方。",
    ]


def test_ftc_heads_up_parser_excludes_english_and_preserves_quoted_questions() -> None:
    pages = [""] * 15
    pages[1] = (
        "要在生活中帮助您的孩子安全上网。\n"
        "每次都扪心自问： “这个应用软件需要知道我的位置吗？ ”\n"
        "如果不需要， 关闭位置\n"
        "To help kids in your life be safe online."
    )
    pages[2] = "3\n共享。\n谨慎分享\n网上的行为会产生真实的后果。"
    pages[14] = "This booklet helps kids socialize safely online."

    rows = parse_ftc_heads_up_pages(pages)

    assert [row[2] for row in rows] == [
        "要在生活中帮助您的孩子安全上网。",
        "每次都扪心自问：“这个应用软件需要知道我的位置吗？”",
        "如果不需要，关闭位置共享。",
        "网上的行为会产生真实的后果。",
    ]


def test_nps_parser_keeps_only_complete_article_paragraph_sentences() -> None:
    content = """<!doctype html><html><body>
    <nav><p>导航噪音。</p></nav>
    <h1 class="page-title">Essential Acadia: Simplified Chinese</h1>
    <div class="Article__Content"><div><p>
    欢迎来到阿卡迪亚国家公园。<br />
    请不要将手机当作地图或手电筒。
    请在 <a href="https://example.test">example.test</a> 上查看当前状
    </p></div></div>
    <footer><p>页脚噪音。</p></footer>
    <p>Last updated: October 6, 2023</p></body></html>""".encode()

    rows = parse_nps_acadia_html(content)

    assert [row[2] for row in rows] == [
        "\u6b22\u8fce\u6765\u5230\u963f\u5361\u8fea\u4e9a\u56fd\u5bb6\u516c\u56ed\u3002",
        "\u8bf7\u4e0d\u8981\u5c06\u624b\u673a\u5f53\u4f5c\u5730\u56fe\u6216\u624b\u7535\u7b52\u3002",
    ]


def test_ready_gov_parser_keeps_main_prose_and_excludes_phone_and_navigation() -> None:
    content = """<!doctype html><html lang="zh-hans"><head>
    <title>洪水 | Ready.gov</title></head><body>
    <nav><p>导航噪音。</p></nav><main>
    <p>洪水可能导致严重损害。</p>
    <ul><li><strong>收到警报后立即撤离。</strong></li>
    <li>如遇紧急情况，打 9-1-1。</li></ul>
    <p>Last Updated: 10/22/2025</p></main>
    <footer><p>页脚噪音。</p></footer></body></html>""".encode()

    rows = parse_ready_gov_html("ready-gov-floods-zh-hans-v1", content)

    assert [row[2] for row in rows] == ["洪水可能导致严重损害。", "收到警报后立即撤离。"]


def test_osha_parser_keeps_only_selected_simplified_pages(monkeypatch: pytest.MonkeyPatch) -> None:
    class Page:
        def __init__(self, text: str) -> None:
            self.text = text

        def extract_text(self) -> str:
            return self.text

    class Reader:
        pages = [Page("Electrical Safety."), Page("这是用电安全指南。切勿接触掉落的架空电线。")]
        metadata = type("Metadata", (), {"author": "OSHA"})()

    monkeypatch.setattr("scripts.import_blind_v2_source_pilot.PdfReader", lambda _: Reader())

    rows = parse_osha_pdf("osha-electrical-safety-simplified-v1", b"pdf")

    assert [row[2] for row in rows] == ["这是用电安全指南。", "切勿接触掉落的架空电线。"]


def test_source_class_is_copied_from_manifest(tmp_path: Path) -> None:
    source = tmp_path / "flores.tar.gz"
    source.write_bytes(flores_archive(["公共资料"], []))
    fixture = manifest("flores-200-zho-hans-v1", source)
    fixture["source_class"] = "public_domain"

    assert build_dataset(fixture, source_file=source)["source_class"] == "public_domain"


def test_project_original_import_validates_input_only_schema(tmp_path: Path) -> None:
    source = tmp_path / "project-source.json"
    source.write_text(
        json.dumps(
            {
                "version": 1,
                "id": "zhtw-project-ui-i18n-v1",
                "created_date": "2026-07-23",
                "authorship": "Codex-drafted input-only fixture pending review.",
                "input_only": True,
                "converter_output_used": False,
                "cases": [{"id": "ui-001", "input": "用户界面"}],
            }
        ),
        encoding="utf-8",
    )
    fixture = manifest("zhtw-project-ui-i18n-v1", source)
    fixture["source_class"] = "project_original"

    dataset = build_dataset(fixture, source_file=source)

    assert dataset["stats"]["by_split"] == {"project_original": 1}
    assert dataset["cases"][0]["input"] == "用户界面"
    assert find_forbidden_keys(dataset) == set()


def test_project_original_source_rejects_expected_text() -> None:
    source = {
        "version": 1,
        "id": "zhtw-project-ui-i18n-v1",
        "created_date": "2026-07-23",
        "authorship": "Input-only fixture.",
        "input_only": True,
        "converter_output_used": False,
        "cases": [{"id": "ui-001", "input": "用户界面", "expected": "使用者介面"}],
    }

    with pytest.raises(ValueError, match="invalid project-original source"):
        parse_project_original(source["id"], json.dumps(source).encode())


@pytest.mark.parametrize(
    ("source_id", "expected_cases"),
    (
        ("flores-200-zho-hans-v1", 2009),
        ("ud-chinese-cfl-v1", 451),
        ("cdc-stacks-111808-v1", 18),
        ("cdc-stacks-120024-v1", 22),
        ("cdc-stacks-116683-v1", 22),
        ("zhtw-project-ui-i18n-v1", 50),
        ("zhtw-project-llm-product-v1", 50),
        ("zhtw-project-it-api-cli-v1", 100),
        ("zhtw-project-formal-llm-semantic-v1", 100),
        ("zhtw-project-formal-entity-guard-v1", 100),
        ("massive-1-0-zh-cn-v1", 15619),
        ("ftc-small-business-simplified-v1", 81),
        ("ftc-heads-up-simplified-v1", 117),
        ("nps-essential-acadia-simplified-v1", 32),
        ("ready-gov-floods-zh-hans-v1", 53),
        ("ready-gov-hurricanes-zh-hans-v1", 53),
        ("ready-gov-earthquakes-zh-hans-v1", 48),
        ("osha-electrical-safety-simplified-v1", 14),
        ("osha-chainsaw-safety-simplified-v1", 20),
        ("osha-work-zone-traffic-simplified-v1", 16),
        ("osha-disaster-falls-simplified-v1", 14),
        ("osha-small-business-consultation-simplified-v1", 22),
        ("osha-disaster-cleanup-simplified-v1", 76),
        ("osha-fallen-workers-family-simplified-v1", 23),
        ("vscode-loc-zh-hans-v1", 15618),
        ("aosp-framework-zh-rcn-v1", 1697),
    ),
)
def test_committed_source_pilots_are_pinned_and_input_only(
    source_id: str, expected_cases: int
) -> None:
    manifest_path = MANIFESTS / f"{source_id}.json"
    dataset_path = EXTERNAL / f"{source_id}.json"
    source_manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    dataset = json.loads(dataset_path.read_text(encoding="utf-8"))

    assert validate_manifest(manifest_path) == []
    assert (
        hashlib.sha256(dataset_path.read_bytes()).hexdigest()
        == source_manifest["normalized_sha256"]
    )
    assert dataset["input_only"] is True
    assert dataset["converter_output_used"] is False
    assert dataset["stats"]["eligible_pending_review"] == len(dataset["cases"]) == expected_cases
    assert find_forbidden_keys(dataset) == set()
    assert all(case["classification"]["domain"] is None for case in dataset["cases"])
    assert all(case["classification"]["risk"] is None for case in dataset["cases"])
